In [2]:
import numpy as np

# Define Mass and Stiffness Matrices
M = np.diag([450, 450, 450, 450])
K = 26519.2 * np.diag([1, 1, 1, 1])

# Initialize variables
n = len(M)
A = np.linalg.inv(M) @ K

# Power Iteration to find eigenvalues and eigenvectors
tol = 1e-19
max_iter = int(1e8)
eigenvalues = np.zeros(n)
eigenvectors = np.zeros((n, n))

for i in range(n):
    b_k = np.random.rand(n)
    for _ in range(max_iter):
        b_k1 = A @ b_k
        b_k1_norm = np.linalg.norm(b_k1)
        b_k = b_k1 / b_k1_norm
        if np.linalg.norm(A @ b_k - b_k1_norm * b_k) < tol:
            break
    eigenvalues[i] = b_k1_norm
    eigenvectors[:, i] = b_k
    A = A - eigenvalues[i] * np.outer(b_k, b_k)

natural_frequencies = np.sqrt(eigenvalues)
mode_shapes = eigenvectors

# Check Orthogonality of Modes
orthogonality_check = mode_shapes.T @ M @ mode_shapes

# Display results
print('Natural Frequencies')
print(natural_frequencies)
print('Modes shapes:')
print(mode_shapes)
print('Generalized Mass Matrix (should be diagonal):')
print(orthogonality_check)


Natural Frequencies
[7.6766891 7.6766891 7.6766891 7.6766891]
Modes shapes:
[[ 0.56075836  0.37843952 -0.07114158  0.73298873]
 [ 0.36468923  0.28519994  0.8155939  -0.34708695]
 [ 0.42842713 -0.87526352  0.1745327   0.14107549]
 [ 0.60745537  0.09673826 -0.54706837 -0.56776393]]
Generalized Mass Matrix (should be diagonal):
[[ 4.50000000e+02  4.69635213e-15 -1.24773365e-14  2.63634175e-16]
 [ 1.35525356e-14  4.50000000e+02 -1.62328481e-14 -9.09115137e-15]
 [-3.12140643e-15 -1.76923906e-14  4.50000000e+02  5.81436254e-15]
 [ 1.73127012e-14  4.94495242e-15 -1.76355852e-15  4.50000000e+02]]
